language: ruby
before_install:
  - gem install bundler
gemfile:
  - Gemfile
rvm:
  - 2.0.0
  - 2.1
  - 2.2.2
  - ruby-head
script:
  - bundle exec rspec spec
env:
  global:
    secure: mxbIKMFHSkQvwoCnRQ0OgL6rr5C5Jx9nP3V/mT2DGxtcIQTF68Mx6GYrffIcrRhDcrI3VfzrjNleAnT0k+RtJvYINn6Ug61431YmEXvRkswKNxNyhk3dYCsQphhir5CuO0vtErSwxoO6LUVSNbjXrHV/VaHXOoLtAr79R7fP9pHakWzFFNsWlgDv599CFZJCTK+o7WcJkU5jOZl2F1GCMpVwE4jDZmBUIb2AfIaqlbdXxDicbiMpN1p0MuLPK8UHFI6PgP7pvzQW/GQ+yaQJNW8ikokPePiPajTXCoIZCmmLpfDRqlw5P/naSK4MqI2FIkrv5joMHuCyUrOLhBbU8B8INpMoSxJoilJQnyyQ3Pz0Bb1N2i0oCiI+iFbmLg2XhamuZ7V/TL1PfyrnZtCMQONnHmNjKDZzREQ4RJIYWcxb3zg1qVKrnSNJ7mihHCnhRHmK5RupG30IRylKYxvgna9Envev+ZPvp/s+7xID3yONazNOB7edmRBN0UWRhSD6SCeyx6NNhqONhVeRqsdrUaR1XePLQG7g1qH4WAFQ0K0GxLIvp+HVtYN7UswOUAL8bCNMQj//IA1OeUdfzWBJkmwjgXLPmcZCWQEJRX5W780YpVF/YKqekO41Qr/igk2sbVwdVn1/fv+pqBkeUvUfxn+260MjDkD8WGif505pRRs=
